# Generated by Django 5.0.6 on 2026-09-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='authorized_parent',
            field=models.ForeignKey(blank=True, help_text='Direct link to an existing parent account authorized for this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_students', to='accounts.parentprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, db_index=True, help_text="Parent/guardian email authorized to link to this student (used when the parent doesn't have an account yet at enrollment time).", max_length=254),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['guardian_email'], name='accounts_st_guardia_208a81_idx'),
        ),
    ]
