# Generated by Django 5.0.6 on 2026-09-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_authorized_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='mentor',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
