# Generated by Django 5.0.6 on 2026-09-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='author_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.mentorprofile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assigned', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_created', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='testscore',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='testscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='testscore',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='students',
            field=models.ManyToManyField(related_name='tests', through='academics.TestScore', to='accounts.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['student', 'status'], name='academics_h_student_8767d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testscore',
            unique_together={('test', 'student')},
        ),
    ]
