# Generated by Django 5.0.6 on 2026-09-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_mentor_alter_user_role_and_more'),
        ('courses', '0002_course_teachers_coursequizattempt_coursequizquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.coursecontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_content_progress', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['completed_at'],
                'unique_together': {('content', 'student')},
            },
        ),
    ]
